---
- name: Install required packages for Grafana
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
  when: ansible_os_family == "Debian"

- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add Grafana repository (Debian/Ubuntu)
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  when: ansible_os_family == "Debian"

- name: Add Grafana repository (RHEL/CentOS)
  yum_repository:
    name: grafana
    description: Grafana repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: 1
    gpgkey: https://packages.grafana.com/gpg.key
  when: ansible_os_family == "RedHat"

- name: Install Grafana
  package:
    name: grafana
    state: present

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: '0644'
  notify: restart grafana

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Wait for Grafana to start
  wait_for:
    port: 3000
    delay: 10
    timeout: 60

- name: Configure Grafana data sources
  grafana_datasource:
    name: "{{ item.name }}"
    grafana_url: "http://localhost:3000"
    grafana_user: "{{ grafana_security.admin_user }}"
    grafana_password: "{{ grafana_security.admin_password }}"
    ds_type: "{{ item.type }}"
    ds_url: "{{ item.ds_url }}"
    is_default: "{{ item.isDefault | default(false) }}"
    state: present
  loop: "{{ grafana_datasources }}"
  #no_log: true

- name: Import Grafana dashboards
  grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "{{ grafana_security.admin_user }}"
    grafana_password: "{{ grafana_security.admin_password }}"
    dashboard_id: "{{ item.dashboard_id }}"
    dashboard_revision: "{{ item.revision_id }}"
    state: present
  loop: "{{ grafana_dashboards }}"
  #no_log: true