---
- name: Create Prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: Create Prometheus system user
  user:
    name: prometheus
    system: true
    shell: /bin/false
    group: prometheus
    createhome: false

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus
  loop:
    - "/etc/prometheus"
    - "/etc/prometheus/rules"
    - "/etc/prometheus/rules.d"
    - "/etc/prometheus/files_sd"
    - "{{ prometheus_data_dir }}"

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Copy Prometheus binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus
  loop:
    - prometheus
    - promtool

- name: Copy Prometheus configs
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    remote_src: yes
    mode: '0644'
    owner: prometheus
    group: prometheus
  loop:
    - consoles
    - console_libraries

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify: restart prometheus

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes