name: Deploy Infrastructure and Configure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Terraform Action (Apply/Destroy)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          fi

      - name: Get EC2 Public IP from Terraform Output
        if: ${{ github.event.inputs.action == 'apply' }}
        id: get_ip
        run: |
          IP=$(terraform output -raw ec2_public_ip)  # Using ec2_public_ip instead of public_ip
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Update Inventory with EC2 Public IP
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          # Update the inventory file with the EC2 public IP
          sed -i "s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${EC2_PUBLIC_IP}/g" ../../ansible/inventory.ini

      - name: Commit updated inventory.ini
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ../../ansible/inventory.ini
          git commit -m "Update Ansible inventory with EC2 Public IP" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  ansible:
    name: Run Ansible Playbook
    needs: terraform
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Checkout code with latest changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Set web_environment dynamically
        run: |
          ENVIRONMENT=${{ github.ref_name }}
          if [ "$ENVIRONMENT" = "main" ]; then
            ENVIRONMENT="prod"
          fi
          echo "Setting web_environment to $ENVIRONMENT"
          sed -i "s/^web_environment: .*/web_environment: ${ENVIRONMENT}/" group_vars/webservers/main.yml

      - name: Set up SSH private key for Ansible (use GitHub secret)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Run Playbook
        run: ansible-playbook playbook.yml --vault-password-file vault_pass.txt